version: '3.8'
services:
    oai-gnb:
        image: oaisoftwarealliance/oai-gnb:2023.w10b
        privileged: true
        container_name: rfsim5g-oai-gnb
        environment:
            RFSIMULATOR: server
            USE_ADDITIONAL_OPTIONS: -E -O --log_config.global_log_options level,nocolor,time --sa
        networks:
            public_net:
                ipv4_address: 192.168.71.150
        volumes:
            - ./gnb.sa.band78.fr1.106PRB.usrpb210.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
networks:
    public_net:
        driver: bridge
        name: rfsim5g-oai-public-net
        ipam:
            config:
                - subnet: 192.168.71.128/26
        driver_opts:
            com.docker.network.bridge.name: "rfsim5g-public"
    traffic_net:
        driver: bridge
        name: rfsim5g-oai-traffic-net
        ipam:
            config:
                - subnet: 192.168.72.128/26
        driver_opts:
            com.docker.network.bridge.name: "rfsim5g-traffic"

